### PR TITLE
ci(docker): initialize docker-ci github action

### PR DESCRIPTION
**Pull request by husni-zuhdi**
🎯 Add `docker-ci` github action workflow to automate image creation and publish

### CODE REVIEW

**Comment by Hazunanafaru** [comment]
@fauzianggoro plz ur review

**Comment by Hazunanafaru** [comment]
@fauzianggoro pls your review again

**Comment by Hazunanafaru** [comment]
@fauzianggoro plz review

**Comment by Hazunanafaru** [comment]
@fauzianggoro sek iki lali di review pack

**Review by fauzianggoro — APPROVED** [review]

**Comment by Hazunanafaru** [comment]
Menggokil!!

**Pull request merged**
