### PR TITLE
restructure and revamp `home` page

### PR DESCRIPTION
**Pull request by Hazunanafaru**
👍 Good job @fauzianggoro for the initial frontend `home` content
🚀  However, I've checked the code and we need  to restructure and clean up the code
🧪 Add simple unit test for `main.js` file

### CODE REVIEW

**Comment by Hazunanafaru** [comment]
@fauzianggoro pls review

**Comment by Hazunanafaru** [comment]
@fauzianggoro please review
Try to make a decent-looking website with Bulma
Still serving as a static web. We will improve by implementing routing in `react`

**Comment by Hazunanafaru** [comment]
Screenshot 2023-02-24 at 18-03-18 Project Garden
Screenshot of the page

**Review by fauzianggoro — APPROVED** [review]
masuk banget lurr

**Pull request merged**
